# Config file for Stage 5 - Channel-wise Wave Characterization

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage05_channel_wave_characterization'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'Laminar_test'

# Name of the output file
STAGE_OUTPUT: 'wavefronts_channel-wise_measures.csv'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [5, 10, 15] # int or None. default 'None' -> randomly selected
PLOT_FORMAT: 'png'

# Wave event name
# 'wavefronts', 'wavemodes'
EVENT_NAME: 'wavefronts'

# Measures to compute
# 'velocity_local', 'direction_local', 'inter_wave_interval_local', 'annotations'
MEASURES: ['annotations', 'direction_local', 'flow_direction_local', 
          'inter_wave_interval_local', 'velocity_local'] 
          
# Velocity/Direction local
################
# simple_3x3, prewitt_3x3, scharr_3x3, sobel_3x3, sobel_5x5, sobel_7x7
KERNEL: 'scharr_3x3'
INTERPOLATE: True
# smoothing factor for the interpolation (0 = no smoothing)
SMOOTHING: 2

# Annotations
#############
# Use include_keys, if they are empty apply ignore_keys
INCLUDE_KEYS: ['wavemode', 'spatial_scale', 'array_location', 'session', 
               'x_coords', 'y_coords', 'highpass_freq', 'lowpass_freq',
               'trial', 'landing_sequence', 'in_successful_trial',
               'previous_unsuccessful_trials', 'trial_start', 'trial_duration',
               'target_01_on', 'target_01_reached',
               'target_02_on', 'target_02_reached',
               'target_03_on', 'target_03_reached',
               'target_04_on', 'target_04_reached',
               'automatic_reward_start',
               'target_01_location', 'target_02_location', 
               'target_03_location', 'target_04_location',
               'target_01_position', 'target_02_position', 
               'target_03_position', 'target_04_position',
               ]
IGNORE_KEYS: ['cluster_algorithm', 'cluster_eps', 'cluster_metric',
              'cluster_min_samples', 'threshold', 'experimental_lab',
              'psd_freq_res', 'psd_overlap', 'psd_fs'
              ]
