# Config file for Stage 1 - Data Entry

# Name of stage, must be identical with folder name
STAGE_NAME: stage01_data_entry

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: Laminar_test

# Name of stage output file.
STAGE_OUTPUT: data.nix

# File format in which all intermediate neo objects are stored
NEO_FORMAT: nix

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: true

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/
DATA_SETS:
    Mo18412002: '/Users/maiaraaraujo/Downloads/template_laminar_waves/tw_synthetic.mat'   # replace!

CURATION_SCRIPT: curate_Laminar_data.py

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [5, 10, 15] # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: png

# pixel size
SPATIAL_SCALE: 0.15  # mm

# specified in the data file
SAMPLING_RATE: 1000 # Hz

# time slice in s
# if None, the entire recording is used
T_START: None
T_STOP: None

# recommend top: ventral
ORIENTATION_TOP: cortical surface
# recommended right: 'lateral' for right hemisphere, 'medial' for left hemisphere
ORIENTATION_RIGHT: lateral

TRIAL: 1

# Metadata
ANNOTATIONS:
    experimental_lab: INT - Marseille
    session: Mo180412002
    array_location: PM    # M1/PMd, V1, V2, DP, 7A


ARRAY_ANNOTATIONS: None

# The keyword arguments are passed as key value pairs.
# Keywords must only contain letters, numbers, underscores, and spaces.
# Values can be strings, int, float, bool, or None.
# Values can also be aranged in 1D objects such as lists, or tuples
# It is possible to specify nested subdict.
KWARGS:
    remove_channel_ids: [0, 1, 2, 27, 28, 29, 30, 31]
    trial_times: # in s
        1: (0, 10)
        #2: (10, 20)
        #3: (0, 30)
    
