# Config file for Stage 5 - Wave Characterization

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage05_wave_characterization'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'Laminar'

# Name of the output file
STAGE_OUTPUT: 'wavefronts_wave-wise_measures.csv'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 30  # in s
PLOT_CHANNELS: [5,10,15]  # int or None. default 'None' -> randomly selected
PLOT_FORMAT: 'png'

# Wave event name
# 'wavefronts', 'wavemodes'
EVENT_NAME: 'wavefronts'

# Measures to compute
# 'label_planar', 'velocity_planar', 'direction_planar', 'inter_wave_interval',
# 'time_stamp', 'duration', 'number_of_triggers', 'annotations'
MEASURES: ['annotations', 'duration', 'number_of_triggers', 'inter_wave_interval',
           'label_planar', 'velocity_planar', 'direction_planar', 'time_stamp']

# Label Planar
##############
ALIGNMENT_THRESHOLD: 0.9

# Direction Planar
##################
# tigger_interolation, optical_flow
DIRECTION_METHOD: 'optical_flow'

# Time Stamp
############
# start, middle, end
TIME_STAMP_POINT: ['start', 'end']

# Annotations
#############
# Use include_keys, if they are empty apply ignore_keys
INCLUDE_KEYS: ['wavemode', 'spatial_scale', 'array_location', 'session', 
               'x_coords', 'y_coords', 'highpass_freq', 'lowpass_freq',
               'trial', 'landing_sequence', 'in_successful_trial',
               'previous_unsuccessful_trials', 'trial_start', 'trial_duration',
               'target_01_on', 'target_01_reached',
               'target_02_on', 'target_02_reached',
               'target_03_on', 'target_03_reached',
               'target_04_on', 'target_04_reached',
               'automatic_reward_start',
               'target_01_location', 'target_02_location', 
               'target_03_location', 'target_04_location',
               'target_01_position', 'target_02_position', 
               'target_03_position', 'target_04_position',
               ]
IGNORE_KEYS: ['cluster_algorithm', 'cluster_eps', 'cluster_metric',
              'cluster_min_samples', 'threshold', 'experimental_lab',
              'psd_freq_res', 'psd_overlap', 'psd_fs'
              ]
